services:
  postgres:
    image: postgres:15
    container_name: inventory_postgres
    restart: unless-stopped
    env_file:
      - .env.production
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: inventory_api
    depends_on:
      - postgres
    env_file:
      - .env.production
    environment:
      NODE_ENV: production
      DB_HOST: postgres    
      DB_SYNC: "false"
      DB_LOGGING: "false"
      PORT: 3000
    ports:
      - "3000:3000"

volumes:
  pgdata:
